### ISSUE TITLE
Python3.8 serializing error: TypeError: cannot pickle '_io.BufferedReader' object

### ISSUE THREAD

**Issue by dgbrunoh** [Frameio/python-frameio-client#26]
When trying to upload a file using the docs recommendation the script triggers the following error:

`Traceback (most recent call last):
  File "frameio.py", line 26, in <module>
    client.upload(asset, file)
  File "/usr/local/lib/python3.8/site-packages/frameioclient/client.py", line 224, in upload
    uploader.upload()
  File "/usr/local/lib/python3.8/site-packages/frameioclient/upload.py", line 33, in upload
    proc.start()
  File "/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 283, in _Popen
    return Popen(process_obj)
  File "/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle '_io.BufferedReader' object`

My quick guess would be the multiprocessing library used on the "upload.py" file, I'm not sure that works on py38.

For the record, I've used python3.7 on the same script and worked fine.

**Comment by dgbrunoh** [comment]
Update: I just noticed the request #23, that fixed my issue.

**Comment by jhodges10** [comment]
This is to be fixed in #35!
